export default {
    ADD_POST: "ADD_POST",
    ADD_MSG: "ADD_MESSAGES",
    FOLLOW: "FOLLOW",
    UNFOLLOW: "UNFOLLOW",
    SET_USERS: "SET_USERS",
    TOGGLE_IS_FETCHING: "TOGGLE_IS_FETCHING",
    SET_PROFILE: "SET_PROFILE",
    SET_AUTH_USER: "SET_AUTH_USER",
    TOGGLE_FOLLOWING: "TOGGLE_FOLLOWING",
    UPDATE_PROFILE_STATUS: "UPDATE_PROFILE_STATUS"
};
