export default {
    ADD_POST: "ADD_POST",
    ADD_MSG: "ADD_MESSAGES",
    UPDATE_NEW_POST_TXT: "UPDATE_NEW_POST_TXT",
    UPDATE_NEW_MSG_TXT: "UPDATE_NEW_MSG_TXT",
    FOLLOW: "FOLLOW",
    UNFOLLOW: "UNFOLLOW",
    SET_USERS: "SET_USERS",
    TOGGLE_IS_FETCHING: "TOGGLE_IS_FETCHING",
    SET_PROFILE: "SET_PROFILE",
    SET_AUTH_USER: "SET_AUTH_USER",
    TOGGLE_FOLLOWING: "TOGGLE_FOLLOWING",
};
